#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

name: "PR update for Cloud-AWS"

# Security: `pull_request_target` events can be risky, but we:
# 1. Only grant write access for checks (a.k.a. check runs).
# 2. We are careful with untrusted inputs (i.e. don't use user-supplied
#    variables in ways vulnerable to shell injection, etc.)
# 3. We don't check out the fork's head ref.
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    paths:
      - 'hadoop-tools/hadoop-aws/**'
      - '.github/workflows/*cloud_aws.yml'
      - '.github/actions/build_image**'
      - '.github/gha-tests/hadoop-aws*excludes.txt'

jobs:
  notify:
    name: "Notify Cloud-AWS"
    permissions:
      actions: read
      checks: write
    uses: ./.github/workflows/tmpl_notify_fork_run.yml
    with:
      source_workflow_id: cloud_aws.yml
      upstream_check_name: S3A Test Summary
      details_check_run_name: Run / precondition
